name: Compilar Instaladores de Un Clic
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Instalar Herramientas
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil
        
    - name: Generar ejecutable Estandar (.exe)
      run: |
        pyinstaller --onefile --uac-admin --name="Evolution_Setup_Standard" Evolution_Setup.py
        
    - name: Generar ejecutable Pro (.exe)
      run: |
        pyinstaller --onefile --uac-admin --name="Evolution_Setup_Pro" Evolution_Setup_Pro.py
        
    - name: Subir Instaladores Compilados
      uses: actions/upload-artifact@v4
      with:
        name: Evolution_Installers_Windows
        path: dist/*.exe
